FROM oven/bun:alpine AS base
WORKDIR /usr/src/app

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .

RUN mkdir -p ./.astro/sessions \
    && chown -R bun:bun ./.astro node_modules

ENV HOST=0.0.0.0
ENV PORT=4321

USER bun
EXPOSE 4321/tcp
CMD [ "bun", "run", "dev", "--", "--host", "0.0.0.0", "--port", "4321" ]
